apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sidekiq.name }}
  labels:
    sidekiq: {{ .Values.sidekiq.name }}
    group: {{ .Values.sidekiq.group }}
spec:
  replicas: {{ .Values.sidekiq.replicaCount }}
  selector:
    matchLabels:
      sidekiq: {{ .Values.sidekiq.name }}
  strategy:
    type: {{ .Values.sidekiq.strategy.type }}      
  template:
    metadata:
      labels:
        sidekiq: {{ .Values.sidekiq.name }}
        group: {{ .Values.sidekiq.group }}
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
        vault.hashicorp.com/agent-inject: "true"        
        # vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-secret-app: "{{ .Values.vault.path }}"        
        vault.hashicorp.com/agent-inject-template-app: |
          {{`{{- with secret`}} "{{ .Values.vault.path }}" {{`-}}`}}
          {{`{{ range $Key, $Value := .Data.data }}export {{$Key}}="{{$Value}}"`}}
          {{`{{ end }}`}}
          {{`{{- end -}}`}}
        vault.hashicorp.com/role: {{ .Values.vault.role }}          
    spec:
      serviceAccountName: app      
      imagePullSecrets:
        {{- range .Values.sidekiq.imagePullSecrets}}
          - name: {{ .name }}
        {{- end }} 
      terminationGracePeriodSeconds: {{ .Values.sidekiq.terminationGracePeriodSeconds }}    
      volumes:
        {{- range .Values.sidekiq.volumes}}
        - name: {{ .name}}
          persistentVolumeClaim: 
            claimName: {{ .pvc.name }}  
        {{- end}}      
      containers:
        - name: {{ .Values.sidekiq.name }}
          image: {{ .Values.sidekiq.container.image }}
          command: ["/bin/bash", "-c"]
          args: ["source /vault/secrets/* && bundle exec sidekiq -r ./config/environment.rb -C ./config/sidekiq.yml"]
          lifecycle:
            preStop:
              exec:
                command: 
                  - bundle
                  - exec
                  - sidekiqctl 
                  - quiet
          imagePullPolicy: {{ .Values.sidekiq.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.sidekiq.container.port }}                 
          volumeMounts:
            {{- range .Values.sidekiq.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end}}