version: '3.7'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    image: gasb:latest
    container_name: gasb_app
    command: "bundle exec puma -C config/puma.rb"
    restart: always
    tty: true
    stdin_open: true
    build:
      context: .      
      dockerfile: ./docker/app/Dockerfile    
    volumes:
      - .:/var/www/app
      - ./download:/var/www/app/public/download
      - ./keys:/var/www/app/keys
    environment:        
      VIRTUAL_HOST: "gasb.app"
    depends_on:
      - db
      - sidekiq
    ports:
      - "9292:9292"
    env_file:
      - .env

  sidekiq:
    <<: *app_base
    container_name: gasb_sidekiq
    command: "bundle exec sidekiq -r ./config/environment.rb  -C config/sidekiq.yml"
    volumes:
       - .:/var/www/app
    ports: []
    depends_on:
      - redis
    env_file:
      - .env            

  redis:
    image: redis
    restart: always
    environment: 
      REDIS_HOST: redis
      REDIS_PORT: 6379      
    command: "redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes"
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    env_file:
      - .env      
            
networks:
  default:
    external:
      name: reverse-proxy

volumes:
  postgres-data: {}
  redis-data: {}