app:
  name: app
  group: app
  replicaCount: 1
  terminationGracePeriodSeconds: 60
  strategy:
    type: RollingUpdate  
  container:
    image: r.kirqe.be/gasb:latest
    port: 9292
  imagePullSecrets:
    - name: regzzz    
  service:
    type: ClusterIP
    port: 9292
  volumes:
    - name: downloads-data
      kind: PersistentVolumeClaim
      mountPath: "/var/www/app/public/downloads"
      pvc:
        name: downloads-pvc
        accessMode: ReadWriteOnce
        storage: 100Mi
    - name: keys-data
      kind: PersistentVolumeClaim
      mountPath: "/var/www/app/keys"
      pvc:
        name: keys-pvc
        accessMode: ReadWriteOnce
        storage: 5Mi  

vault:
  role: gasb-role
  path: secret/data/gasb/app