ingress:
  name: ingress
  hosts:
    - host: example.org
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 9292
  tls:
    - hosts:
      - "example.org"
      secretName: example-org-tls
