apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
    group: {{ .Values.postgres.group }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  strategy:
    type: {{ .Values.postgres.strategy.type }}      
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
        group: {{ .Values.postgres.group }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.postgres.terminationGracePeriodSeconds }}
      volumes:
        - name: {{ .Values.postgres.volume.name }}
          persistentVolumeClaim: 
            claimName: {{ .Values.postgres.volume.pvc.name }}            
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.container.image }}
          ports: 
            - containerPort: {{ .Values.postgres.container.port }}
          envFrom: 
            - configMapRef:
                name: {{ .Values.postgres.config.name }}
            - secretRef:
                name: {{ .Values.postgres.secret.name }}                
          volumeMounts:
            - name: {{ .Values.postgres.volume.name }}
              mountPath: {{ .Values.postgres.volume.mountPath }}                      