app:
  name: app
  group: app
  replicaCount: 1
  terminationGracePeriodSeconds: 60
  strategy:
    type: RollingUpdate  
  container:
    image: gasb:1.1   
    imagePullPolicy: Never
    port: 9292
  imagePullSecrets:
    - name: regcred    
  service:
    type: ClusterIP
    port: 9292
  volumes:
    - name: downloads-data
      kind: PersistentVolumeClaim
      mountPath: public/downloads
      pvc:
        name: downloads-persistent-volume-claim
        accessMode: ReadWriteOnce
        storage: 100Mi  
  config:
    name: app-config
    data:
      - key: key
        value: value
  secret:
    name: app-secret
    data: 
      - key: key
        value: value
    


