# NAME: ""
# DESCRIPTION: ""
# IMAGE: ""
# SUMMARY_IMAGE: ""

# GA: ""
# G_CAPT_KEY: ""

# BASE_URL: ""

# PADDLE_VENDOR_ID: 
# PADDLE_AUTH_CODE: ""

# JWT_SECRET: ""
# JWT_ISSUER: ""
# JWT_TTL: 20

# REDIS_URL: ""
# SIDEKIQ_UN: ""
# SIDEKIQ_PS: ""

# RACK_SECRET: ""

# SERVICE_ACCOUNT: ""
# SUPPORT_EMAIL: ""

# MAILER_FROM: ""
# MAILER_HOSTNAME: ""
# MAILER_PORT: 587
# MAILER_USERNAME: ""
# MAILER_PASSWORD: ""
# MAILER_DOMAIN: ""

# POSTGRES_USER: ""
# POSTGRES_PASSWORD: ""
# POSTGRES_PORT: ""
# POSTGRES_HOST: ""