default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: gasb_prod
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: gasb_prod

test:
  <<: *default
  database: gasb_prod