redis:
  name: redis
  group: db
  replicaCount: 1
  terminationGracePeriodSeconds: 60
  strategy:
    type: RollingUpdate  
  container:
    image: redis
    command: ["redis-server"]
    args: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)", "--appendonly", "yes"]
    port: 6379
  service:
    type: ClusterIP
    port: 6379
  volume:
    name: redis-data
    kind: PersistentVolumeClaim
    mountPath: /var/lib/redis/data
    pvc:
      name: redis-persistent-volume-claim
      accessMode: ReadWriteOnce
      storage: 1Gi
  config:
    name: redis-config
    data:
      - key: key
        value: value
  secret:
    name: redis-secret
    data: 
      - key: key
        value: value