name: trigger jenkins job
on:
  push:
    branches: [master]
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jen.kirqe.be"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "gasb"
